services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:18
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    command: sleep infinity
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/staple
      WATCHPACK_POLLING: "true"
      NEXT_TELEMETRY_DISABLED: "1"

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: staple
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
