name: Build and Test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies and generate Prisma client
        run: |
          npm install
          npx blitz prisma generate

      - name: Run build
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        run: npm run build
